# -*- coding: utf-8 -*-
"""denoise-image

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MYwe9F6bTjI7LRYN_I01gx2qd3FfTKKz
"""

import cv2
import matplotlib.pyplot as plt

def denoise(image_path):
    # Load the noisy image
    noisy_image = cv2.imread(image_path)
    noisy_image = cv2.cvtColor(noisy_image, cv2.COLOR_BGR2RGB)

    # Apply Gaussian denoising
    gaussian_denoised_image = cv2.GaussianBlur(noisy_image, ksize=(5, 5), sigmaX=5)
    gaussian_denoised_image = cv2.cvtColor(gaussian_denoised_image, cv2.COLOR_BGR2RGB)

    # Apply median denoising
    median_denoised_image = cv2.medianBlur(noisy_image, ksize=5)
    median_denoised_image = cv2.cvtColor(median_denoised_image, cv2.COLOR_BGR2RGB)

    # Display the images
    plt.figure(figsize=[15, 8])

    plt.subplot(1, 3, 1)
    plt.imshow(noisy_image)
    plt.title("Noisy Image")

    plt.subplot(1, 3, 2)
    plt.imshow(gaussian_denoised_image)
    plt.title("Gaussian Denoised")

    plt.subplot(1, 3, 3)
    plt.imshow(median_denoised_image)
    plt.title("Median Denoised")

    plt.show()

# Call the denoise function with the path to the noisy image
denoise('noisy.png')